appid: productSvc
retry_dead_threshold: 130000
rollback_retry_timeout_unlock_enable: true
etcd_config:
  endpoints:
    - localhost:2379
tm:
  commitRetryCount: 5
  rollbackRetryCount: 5
at:
  dsn: "root:123456@tcp(127.0.0.1:3306)/product?timeout=5s&readTimeout=5s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
  reportRetryCount: 5
  reportSuccessEnable: false
  lockRetryInterval: 5ms
  lockRetryTimes: 30
